name: "template"

services:
  backend:
    container_name: "pattern-backend"
    image: "local/template/backend"
    build:
      context: backend
    ports:
      - "8080:8080"
      - "8081:8081" # actuator
    environment:
      JAVA_OPTS: >
        -XX:InitialRAMPercentage=50
        -XX:MaxRAMPercentage=75
        -XX:MinRAMPercentage=25
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -XX:+UseG1GC 
        -XX:MaxGCPauseMillis=200
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/heapdump.hprof
      SPRING_OPTS: "--spring.profiles.active=local"
      DB_USER: $DB_USER
      DB_PWD: $DB_PWD
      DB_NAME: $DB_NAME
      DB_HOST: db
      DB_PORT: 5432
      DB_SCHEMA: template
      ALLOWED_CORS: "http://localhost:4200;http://localhost:8080;http://localhost:8090;http://template.localhost;http://template-static.localhost"
      CLIENT_ID: "$CLIENT_ID"
      CLIENT_SECRET: "$CLIENT_SECRET"
    depends_on:
      liquibase:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  db:
    container_name: "pattern-db"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    container_name: "pattern-liquibase"
    image: "liquibase:latest"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/$DB_NAME
      LIQUIBASE_COMMAND_USERNAME: $DB_USER
      LIQUIBASE_COMMAND_PASSWORD: $DB_PWD
    command: ["--defaults-file=/liquibase/liquibase.properties", "update"]

  frontend:
    container_name: "pattern-frontend"
    image: node:24
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    command: sh -c "npm i && npm run start"

  frontend-nginx:
    container_name: "pattern-frontend-nginx"
    image: "local/template/frontend-nginx"
    build:
      context: frontend
    ports:
      - "8090:80"

  postgres-keycloak:
    container_name: "pattern-postgres-keycloak"
    image: "postgres:17"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./keycloak/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', "pg_isready", "-U", "keycloak"]
      interval: 5s
      retries: 5
      timeout: 3s

  keycloak:
    container_name: "pattern-keycloak"
    image: "quay.io/keycloak/keycloak:26.4.0"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "kcadm"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "password"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY: edge
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8987:8080"
      - "8988:9000"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/template-realm.json:/opt/keycloak/data/import/realm-template.json:ro
    healthcheck:
      test: ["CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"]
      interval: 5s
      retries: 10
      timeout: 3s

  reverse-proxy:
    container_name: "pattern-reverse-proxy"
    image: "local/template/reverse-proxy"
    ports:
      - "80:8080"
    build:
      context: reverse-proxy

volumes:
  node_modules_cache: