spring.application.name=DemoProxy
info.app.version=@project.version@
info.app.build-time=@build-time@

management.endpoints.web.exposure.include=health,loggers,prometheus,heapdump,threaddump
management.server.port=8081
management.endpoints.web.base-path=/actuator